apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chetan2-poi-map-app-dev
  annotations:
    argocd/app-name: chetan2-poi-map-app-dev
    backstage.io/kubernetes-id: chetan2-poi-map-app
    backstage.io/kubernetes-namespace: chetan2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/chetan2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/chetan2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/chetan2/deployments/chetan2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/chetan2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://chetan2-poi-map-app-chetan2.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-chetan2
  consumesApis:
    - gateway-api-chetan2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-chetan2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
